name: Eoko's Blog
description: Blogging about dev, php, js and web application
meta_description: "Your New Jekyll Site, Blogging about stuffs"

aboutPage: true

exclude: [vendor]

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  hard_wrap: false
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  syntax_highlighter_opts:
      line_numbers: false
      wrap: true


paginate: 10
baseurl: /
domain_name: 'http://blog.eoko.fr'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url: 'http://blog.eoko.fr'

authors:
  hanzou:
    name: Hanzou Hattori
    display_name: Hanzou
    gravatar: c66919cb194f96c696c1da0c47354a6a
    email: hanzou@company.com
    web: http://company.com
    twitter: company
    github: hhattori
  jorgen:
    name: Jörgen Mortensen
    display_name: Jörgen
    gravatar: 12e480a364a5c19214f99b4dfe9a11d5
    email: jorgen@company.com
    web: http://company.com
    twitter: company
    github: jorgenm

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
gems:
  - jekyll-sitemap
